### ISSUE TITLE
image.tag might provide a confusing tag

### ISSUE THREAD

**Issue by vkurup** [caktus/invoke-kubesae#7]
`image.tag` creates a tag which is based on the current branch name, and the HEAD commit on that branch. So, if you make changes without committing them, the tag will NOT change. But the `image.build` command builds whatever is in your working directory. This can lead to cases where you push a different image to the registry that has the exact same tag.

This seems to only happen while someone is testing out deployment commands. In a "real" situation, deployments would only be done on CI, or right after a merge to develop or master, but maybe it would be worth checking for a dirty git tree and warning the user that they should stash or commit changes before deploying.

**Comment by dpoirier** [comment]
What if instead of using `git rev-parse`, we used `git describe --all
--dirty` to come up with the tag? Then it'd include "-dirty" on the end if
the local source was dirty.


*Dan Poirier*Django Developer

dpoirier@caktusgroup.com
www.caktusgroup.com

**Comment by vkurup** [comment]
That's an interesting approach. But `git describe --all --dirty` doesn't quite do what I'd expect. It doesn't seem to care about untracked files:

```
$ git describe --all --dirty
heads/master
$ touch a-new-file
$ git describe --all --dirty
heads/master
```
Is there a version of that command that does?

**Comment by dpoirier** [comment]
I guess we could see if there's any output from "git clean --dry-run".

>

**Comment by vkurup** [comment]
Yes, or we could use `git status` like I did in the PR (#8), but instead use that to amend the tag name, rather than just emitting a warning. I'll make that change
