### ISSUE TITLE
invoke pod.debian doesn't work

### ISSUE THREAD

**Issue by vkurup** [caktus/invoke-kubesae#9]
At least for me (Ubuntu 20.04, bash), it just hangs:
```
$ inv pod.debian 
kubectl delete pod debian
Error from server (NotFound): pods "debian" not found
kubectl run -it debian --image=debian:bullseye-slim --restart=Never -- bash
Unable to use a TTY - input is not a terminal or the right kind of file
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: 
** Ctrl-C **
```

This works though:
```
$ kubectl run --stdin --tty debian --image=debian:bullseye-slim --restart=Never -- bash
If you don't see a command prompt, try pressing enter.
root@debian:/# 
```

Should I change the command to use `--stdin --tty` instead of `-it`? Or is there some other way to make this command work for me?

**Comment by JeremyGibson** [comment]
Interesting. Still works for me on 18.04, but yours does as well. So if it works for everyone, I say make the change.

**Comment by vkurup** [comment]
Actually, I was wrong. Both versions work from my command line, but fail for me when `inv pod.debian` runs them. I'll keep investigating...

**Comment by JeremyGibson** [comment]
Wait. I use zsh. let me switch to bash and see what happens.

**Comment by JeremyGibson** [comment]
works with bash on 18.04 using `inv pod.debian`

**Comment by vkurup** [comment]
Ahh, i just noticed something. That `pty: True` that is in invoke.yaml seems to fix it. I added it to my tasks.py, like this and then it worked:
```
-        "run": {"echo": True,},
+        "run": {"echo": True, "pty": True},
```

**Comment by JeremyGibson** [comment]
interesting. Must be something with Bash5. I looked through the change log and nothing jumped out

**Comment by vkurup** [comment]
I think it's this: http://www.pyinvoke.org/faq.html#why-is-my-command-behaving-differently-under-invoke-versus-being-run-by-hand

If you set `pty:True` (either in the tasks.py, or in [invoke.yaml](https://github.com/caktus/invoke-kubesae/blob/master/invoke.yaml)), it works.
